"use client";

import { useMemo, useState } from "react";

type View = "priorities" | "orchestration" | "controls" | "capacity" | "learning";
type Filter = "All" | "Healthcare" | "Financial services" | "Logistics" | "Software";
type Phase = "prioritized" | "routed" | "cleared" | "capacity" | "rule";
type TaskKind = "priority" | "collision" | "identity" | "approval" | "capacity" | "rule";
type Task = { account: string; kind: TaskKind; title: string; evidence: string; proposal: string; handoff: string; phase: Phase };

const accounts = [
  { account: "Northstar Health", industry: "Healthcare", owner: "Morgan Smith", groups: 4, people: 18, value: "$4.2M", need: "Sponsor path stalled while technical adoption grows.", action: "Set priority" },
  { account: "Cedar & Finch", industry: "Financial services", owner: "Alex Chen", groups: 3, people: 14, value: "$1.8M", need: "Brand and legal review is blocking a ready audience plan.", action: "Set priority" },
  { account: "Meridian Logistics", industry: "Logistics", owner: "Samira Jones", groups: 6, people: 43, value: "$2.6M", need: "Event follow-up and product-release activity target the same group.", action: "Set priority" },
  { account: "Harborline Bank", industry: "Financial services", owner: "Data operations", groups: 2, people: 18, value: "$1.1M", need: "Identity matching is holding eligible people from activation.", action: "Set priority" },
  { account: "Asteria Cloud", industry: "Software", owner: "Priya Shah", groups: 5, people: 31, value: "$3.7M", need: "A high-value buying group has no active business-owner path.", action: "Set priority" },
];

const viewCopy: Record<View, { eyebrow: string; title: string; detail: string }> = {
  priorities: { eyebrow: "Portfolio prioritization", title: "What must move today?", detail: "Rank enterprise work by value, urgency, risk and the capacity required to act." },
  orchestration: { eyebrow: "Work orchestration", title: "Connect the work before it collides.", detail: "Coordinate account plans, releases, campaigns and sales motions around each buying group." },
  controls: { eyebrow: "Exceptions and controls", title: "Resolve what cannot safely proceed on its own.", detail: "Surface policy, consent, data and approval exceptions that require human judgment." },
  capacity: { eyebrow: "Capacity and service levels", title: "Protect the team’s ability to deliver.", detail: "Balance work across campaign operations, marketing automation, analytics and regional teams." },
  learning: { eyebrow: "Performance and learning", title: "Turn outcomes into better operating rules.", detail: "See which decisions improve AAR, pipeline value, velocity and release-ready cadence." },
};

const taskOptions: Record<TaskKind, string[]> = {
  priority: ["Keep the recommended priority and owner", "Raise priority and add executive coverage", "Defer until the next portfolio review"],
  collision: ["Combine both activities into one coordinated sequence", "Let the product-release plan lead and suppress event follow-up", "Keep both activities and escalate the conflict"],
  identity: ["Approve the proposed account matches and release eligible people", "Keep the audience held and assign a data steward", "Exclude the ambiguous records and release the confirmed matches"],
  approval: ["Approve the proposed path and release it to delivery", "Return it to the owners with required changes", "Escalate the exception to the approval council"],
  capacity: ["Move two approval specialists to Marketing Automation", "Delay the next release window until capacity is available", "Keep current allocation and accept the SLA risk"],
  rule: ["Apply the recommendation to eligible expansion plans", "Run a limited pilot before changing the operating rule", "Keep the current rule and monitor for two weeks"],
};

function taskFor(account: string, kind: TaskKind): Task {
  const item = accounts.find((candidate) => candidate.account === account);
  const value = item?.value ?? "$0";
  const shared = { account, kind, phase: kind === "identity" || kind === "approval" ? "cleared" as Phase : kind === "collision" ? "routed" as Phase : kind === "capacity" ? "capacity" as Phase : kind === "rule" ? "rule" as Phase : "prioritized" as Phase };
  if (kind === "collision") return { ...shared, title: `Resolve the activity collision — ${account}`, evidence: "Event follow-up and product-release activity are both scheduled for the same buying group within 24 hours.", proposal: "Create one coordinated sequence, preserve the release moment and suppress the duplicate message.", handoff: "The selected sequence will be routed to campaign operations, sales and Adobe Marketo / AJO." };
  if (kind === "identity") return { ...shared, title: `Resolve identity exception — ${account}`, evidence: "18 people are held because the account match is incomplete. No activation can proceed for ambiguous records.", proposal: "Release only people with a confirmed match and create a data-steward task for the remainder.", handoff: "The eligible audience will route to the existing account plan; held records remain in the data-quality queue." };
  if (kind === "approval") return { ...shared, title: `Decide the approval path — ${account}`, evidence: "The sponsor brief meets the content rule but needs its named brand and legal approvals before release.", proposal: "Route the approved brief to its reviewers, with the launch held until both responses are recorded.", handoff: "A Workfront review package will be created and the release status will update for the account owner." };
  if (kind === "capacity") return { ...shared, title: "Rebalance Marketing Automation capacity", evidence: "Marketing Automation is at 91% capacity and approval work is putting the next release window at risk.", proposal: "Move two approval specialists from Campaign Operations for the next release window.", handoff: "The workload, service level and release forecast will be recalculated immediately." };
  if (kind === "rule") return { ...shared, title: "Set the sponsor-message operating rule", evidence: "Across 47 eligible buying groups, sponsor engagement is 18% higher when an operating outcome leads the plan.", proposal: "Use business-value messaging as the recommended starting point for eligible expansion plans.", handoff: "The rule will guide new plan recommendations and remain available for governance review." };
  return { ...shared, title: `Set portfolio priority — ${account}`, evidence: `${value} potential impact across ${item?.groups ?? 0} buying groups and ${item?.people ?? 0} people. ${item?.need ?? ""}`, proposal: `Keep ${item?.owner ?? "the assigned owner"} accountable for the next decision and coordinate the needed work around the buying group.`, handoff: "The account will enter the coordinated-work queue with its owner, service level and dependencies." };
}

export default function CommandCenter({ onOpenMorgan }: { onOpenMorgan: () => void }) {
  const [view, setView] = useState<View>("priorities");
  const [filter, setFilter] = useState<Filter>("All");
  const [phases, setPhases] = useState<Record<string, Phase>>({});
  const [activity, setActivity] = useState<string[]>(["41 routine checks completed automatically within policy."]);
  const [notice, setNotice] = useState("The system has prioritized today’s portfolio work and isolated the decisions that need your judgment.");
  const [task, setTask] = useState<Task | null>(null);
  const visibleAccounts = useMemo(() => filter === "All" ? accounts : accounts.filter((item) => item.industry === filter), [filter]);
  const openTask = (next: Task) => { setTask(next); setNotice(`Opened a decision workspace: ${next.title}.`); };
  const completeTask = (choice: string) => {
    if (!task) return;
    setPhases((current) => ({ ...current, [task.account]: task.phase }));
    const result = `${task.account}: ${choice}`;
    setActivity((current) => [result, ...current].slice(0, 3));
    setNotice(`${choice}. ${task.handoff}`);
    setTask(null);
  };
  const reset = () => { setView("priorities"); setFilter("All"); setPhases({}); setActivity(["New portfolio inquiry started. The system rebuilt today’s active decision queue."]); setTask(null); setNotice("New portfolio inquiry started. The system reset the working queue to today’s highest-value enterprise decisions."); };
  const selected = viewCopy[view];

  return <main className="command-center">
    <header className="command-topbar"><span className="command-brand">ChatGPT Work</span><span className="command-topbar-title">Enterprise marketing</span><span className="command-avatar">M</span></header>
    <div className="command-desktop">
      <aside className="command-sidebar"><button className="command-new-chat" onClick={reset}><span>＋</span> New chat</button><button className="command-thread-active" onClick={() => setNotice("You are in the enterprise command center: the portfolio-level operating view.")}><span>◫</span> Command center</button><span className="command-sidebar-label">Project</span><button className="command-project" onClick={() => setNotice("Enterprise adoption scope: 386 accounts, 2,148 buying groups and the operating rules that connect marketing and sales.")}><span>▣</span> Enterprise adoption</button><span className="command-sidebar-label">Recent</span><button onClick={onOpenMorgan}>Morgan’s workspace</button><button onClick={() => { setView("orchestration"); setNotice("Campaign brief opened in the work orchestration view, where its dependencies and account impact can be reviewed."); }}>Campaign brief</button></aside>
      <div className="command-thread"><div className="command-thread-intro"><span>09:30 · Marketing operations</span><p>What needs to move across the enterprise today?</p></div><div className="command-agent-reply"><span>✳</span><p><b>Marketing operations agent</b><br />{notice}</p></div>
        <section className="command-artifact" aria-label="Enterprise marketing operations command center">
          <section className="command-hero"><div><span className="command-eyebrow">Enterprise orchestration and intelligence</span><h1>Keep the highest-value work moving.</h1><p>This is the operating layer across accounts, buying groups, people, teams and channels. It prioritizes, connects, checks and routes work so the organization can act at enterprise scale.</p></div><aside className="command-brief"><span className="command-eyebrow">System recommendation</span><b>Unblock $6.0M in sponsor-path decisions</b><p>Two high-value buying groups are ready for a business-value decision. The underlying account work is assembled.</p><button onClick={onOpenMorgan}>Open Northstar’s workspace →</button></aside></section>
          <div className="command-scale">386 enterprise accounts <span>·</span> 2,148 buying groups <span>·</span> 31,602 people <span>·</span> 26 active coordinated workflows</div>
          <section className="command-metrics"><article><span>Value realization · AAR</span><strong>$38.4M</strong><small>Illustrative AAR created and realized</small></article><article><span>Pipeline value</span><strong>$486M</strong><small>Qualified enterprise pipeline, including expansion</small></article><article><span>Pipeline velocity</span><strong>42 days</strong><small>From engaged buying group to next decision</small></article><article className="command-metric-attention"><span>Release-ready cadence</span><strong>6.4 days</strong><small>Product release to approved enterprise action</small></article></section>
          <nav className="command-views" aria-label="Operations workflows">{(Object.keys(viewCopy) as View[]).map((item) => <button key={item} className={view === item ? "active" : ""} onClick={() => setView(item)}>{viewCopy[item].eyebrow}</button>)}</nav>
          <div className="command-filters"><span>View by</span>{(["All", "Healthcare", "Financial services", "Logistics", "Software"] as Filter[]).map((item) => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div>
          {task && <DecisionWorkspace task={task} onCancel={() => setTask(null)} onComplete={completeTask} />}
          <section className="command-operation"><header className="command-operation-header"><div><span className="command-eyebrow">{selected.eyebrow}</span><h2>{selected.title}</h2><p>{selected.detail}</p></div><span className="command-attention-count">{Object.keys(phases).length ? `${Object.keys(phases).length} decisions applied` : "5 decisions need attention"}</span></header>{view === "priorities" ? <PortfolioView accounts={visibleAccounts} phases={phases} onOpenMorgan={onOpenMorgan} onTask={openTask} /> : view === "orchestration" ? <OrchestrationView onOpenMorgan={onOpenMorgan} onTask={openTask} phases={phases} /> : view === "controls" ? <ControlsView onTask={openTask} phases={phases} /> : view === "capacity" ? <CapacityView onTask={openTask} balanced={phases["Marketing Automation"] === "capacity"} /> : <LearningView onTask={openTask} active={phases["Sponsor-message rule"] === "rule"} />}</section>
          <section className="command-system-log"><div><span className="command-eyebrow">Operating record</span><b>{activity[0]}</b></div><ol>{activity.slice(1).map((entry) => <li key={entry}>{entry}</li>)}</ol></section>
        </section><div className="command-composer">Ask about portfolio performance, a specific account, or today’s operating decisions…</div>
      </div>
    </div>
  </main>;
}

function DecisionWorkspace({ task, onCancel, onComplete }: { task: Task; onCancel: () => void; onComplete: (choice: string) => void }) {
  const [choice, setChoice] = useState(""); const [note, setNote] = useState("");
  return <section className="decision-workspace" aria-label={task.title}><header><div><span className="command-eyebrow">Decision workspace</span><h2>{task.title}</h2></div><button onClick={onCancel}>Close</button></header><div className="decision-workspace-context"><article><span>What the system found</span><p>{task.evidence}</p></article><article><span>System proposal</span><p>{task.proposal}</p></article><article><span>What happens next</span><p>{task.handoff}</p></article></div><fieldset><legend>Choose a resolution</legend>{taskOptions[task.kind].map((option) => <label key={option}><input type="radio" name="task-choice" value={option} checked={choice === option} onChange={() => setChoice(option)} /> <span>{option}</span></label>)}</fieldset><label className="decision-note">Decision note <textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add context to the decision record (optional)" /></label><footer><button onClick={onCancel}>Cancel</button><button disabled={!choice} onClick={() => onComplete(note ? `${choice} Note: ${note}` : choice)}>Confirm and route work →</button></footer></section>;
}

function PortfolioView({ accounts: items, phases, onOpenMorgan, onTask }: { accounts: typeof accounts; phases: Record<string, Phase>; onOpenMorgan: () => void; onTask: (task: Task) => void }) { const active = items.filter((item) => !phases[item.account]); const moved = items.filter((item) => phases[item.account]); return <div className="command-portfolio"><div className="command-portfolio-scale"><span>Prioritized by combined enterprise impact</span><div><b>1</b> AAR potential <b>2</b> pipeline value <b>3</b> velocity risk <b>4</b> release urgency</div></div>{active.map((item, index) => <article key={item.account}><strong>{String(index + 1).padStart(2, "0")}</strong><div><span>{item.industry} · {item.groups} buying groups · {item.people} people</span><h3>{item.account}</h3><p>{item.need}</p></div><div className="command-impact"><span>Potential impact</span><b>{item.value}</b></div><div className="command-priority-action">{item.account === "Northstar Health" ? <button onClick={onOpenMorgan}>Open account plan →</button> : <button onClick={() => onTask(taskFor(item.account, "priority"))}>{item.action} →</button>}</div></article>)}{moved.length > 0 && <div className="command-moved"><b>Moved from today’s priority queue</b>{moved.map((item) => <span key={item.account}>{item.account} · {phases[item.account]}</span>)}</div>}</div>; }
function OrchestrationView({ onOpenMorgan, onTask, phases }: { onOpenMorgan: () => void; onTask: (task: Task) => void; phases: Record<string, Phase> }) { const plans = [{ account: "Northstar Health", trigger: "Sponsor gap + technical adoption", work: ["Account plan", "Sales outreach", "Sponsor brief"], owner: "Morgan Smith", action: "Open coordinated plan" }, { account: "Meridian Logistics", trigger: "Event follow-up + product release", work: ["Launch plan", "Event sequence", "Sales task"], owner: "Samira Jones", action: "Resolve collision" }, { account: "Cedar & Finch", trigger: "Approved audience + pending review", work: ["Audience", "Brand review", "Legal review"], owner: "Alex Chen", action: "Review approval" }]; return <div className="command-orchestration"><div className="command-orchestration-key"><span><i /> Connected work</span><span><i /> Dependency</span><span><i /> Human decision</span></div>{plans.map((plan) => <article key={plan.account} className={phases[plan.account] === "routed" ? "is-routed" : ""}><header><div><span>Buying-group play · {plan.trigger}</span><h3>{plan.account}</h3></div><b>{plan.owner}</b></header><div className="command-flow">{plan.work.map((step, index) => <div key={step}><span>{step}</span>{index < plan.work.length - 1 && <i>→</i>}</div>)}<em>→</em><strong>{phases[plan.account] === "routed" ? "Routed to delivery" : "Coordinated next action"}</strong></div><footer><p>{phases[plan.account] === "routed" ? "The work is now connected across the account plan, campaign operation and sales task." : "The system combined related work and checked for conflicting activity before routing this plan."}</p>{plan.account === "Northstar Health" ? <button onClick={onOpenMorgan}>{plan.action} →</button> : phases[plan.account] === "routed" ? <b className="command-applied">Routed</b> : <button onClick={() => onTask(taskFor(plan.account, plan.account === "Meridian Logistics" ? "collision" : "approval"))}>{plan.action} →</button>}</footer></article>)}</div>; }
function ControlsView({ onTask, phases }: { onTask: (task: Task) => void; phases: Record<string, Phase> }) { const exceptions = [{ account: "Harborline Bank", kind: "identity" as TaskKind, type: "Identity and eligibility", severity: "High", action: "Resolve data exception" }, { account: "Cedar & Finch", kind: "approval" as TaskKind, type: "Approval policy", severity: "Medium", action: "Review approval path" }, { account: "Meridian Logistics", kind: "collision" as TaskKind, type: "Activity collision", severity: "Medium", action: "Resolve collision" }]; const open = exceptions.filter((item) => phases[item.account] !== "cleared" && phases[item.account] !== "routed"); return <div className="command-controls"><div className="command-control-summary"><b>{open.length ? `${open.length} consequential exceptions` : "No consequential exceptions remain"}</b><span>{open.length ? "41 routine policy checks were completed automatically. These cases need an accountable decision." : "The remaining work is within policy and continues through coordinated delivery paths."}</span></div>{open.map((item) => <article key={item.account}><div className="command-exception-mark">!</div><div><span>{item.type}</span><h3>{item.account} <b className={item.severity === "High" ? "high" : ""}>{item.severity}</b></h3><p>{taskFor(item.account, item.kind).evidence}</p><small><b>System action:</b> {taskFor(item.account, item.kind).proposal}</small></div><button onClick={() => onTask(taskFor(item.account, item.kind))}>{item.action} →</button></article>)}</div>; }
function CapacityView({ onTask, balanced }: { onTask: (task: Task) => void; balanced: boolean }) { const teams = [["Campaign operations", "18", "3", "74%", "Healthy"], ["Marketing automation", "14", balanced ? "3" : "5", balanced ? "76%" : "91%", balanced ? "Healthy" : "At risk"], ["Analytics & data", "9", "2", "68%", "Healthy"], ["Field & regional", "22", "7", "84%", "Watch"]]; return <div className="command-capacity"><div className="command-capacity-summary"><b>{balanced ? "Capacity plan is active." : "Three workflows are approaching their service-level threshold."}</b><span>{balanced ? "Two approval specialists are now assigned to marketing automation for the next release window." : "Shift approval capacity to marketing automation before the next product-release window."}</span>{balanced ? <span className="command-applied">Applied</span> : <button onClick={() => onTask(taskFor("Marketing Automation", "capacity"))}>Review capacity plan →</button>}</div>{teams.map(([team, people, workflows, load, status]) => <article key={team}><div><h3>{team}</h3><span>{people} people · {workflows} active workflows</span></div><div className="command-load"><i><em style={{ width: load }} /></i><b>{load} capacity</b></div><strong className={status === "At risk" ? "at-risk" : ""}>{status}</strong></article>)}</div>; }
function LearningView({ onTask, active }: { onTask: (task: Task) => void; active: boolean }) { return <div className="command-learning-grid"><article className={active ? "is-applied" : ""}><span>Signal</span><h3>Business-value messaging earns the strongest sponsor response.</h3><p>Across 47 eligible buying groups, sponsor engagement is 18% higher when an operating outcome leads the plan.</p>{active ? <b className="command-applied">Rule active for eligible expansion plans</b> : <button onClick={() => onTask(taskFor("Sponsor-message rule", "rule"))}>Review and apply rule →</button>}</article><article><span>Friction</span><h3>Approval wait time is the main release-cadence constraint.</h3><p>Marketing automation is at 91% capacity. Rebalancing review work would recover an estimated 1.3 days.</p><button onClick={() => onTask(taskFor("Marketing Automation", "capacity"))}>Open capacity decision →</button></article><article><span>Decision</span><h3>Increase priority for expansion groups with technical adoption.</h3><p>Technical engagement plus an identified sponsor gap is the strongest current signal for near-term expansion value.</p><button onClick={() => onTask(taskFor("Asteria Cloud", "priority"))}>Open priority decision →</button></article></div>; }
