"use client";
import { useEffect, useState } from "react";
import { finservMeasures, finservResult, initialFinserv, type FinservInput } from "../lib/finserv";
import "./finserv.css";
const storageKey = "finserv-activation-v1";
const journeys = [
  { title: "Top 20", audience: "Finance prospects in the Top 20 account list · buying-group members", steps: ["Account/persona ad", "Tailored landing page · email capture", "Leaders Guide email", "Confirmed download", "Virtual roundtable invitation", "Account Director context and follow-up"] },
  { title: "Broader market", audience: "All finance prospects, including Top 20 accounts", steps: ["Prospect ad", "Financial-workflow page · email capture", "Guide email", "Confirmed download", "Webinar invitation", "Event follow-through and nurture"] },
];
export default function FinservWorkflow() {
  const [tab, setTab] = useState("Journey");
  const [input, setInput] = useState<FinservInput>(initialFinserv);
  const [role, setRole] = useState("Business sponsor");
  const [ready, setReady] = useState(false);
  const [notice, setNotice] = useState("");
  useEffect(() => { try { const raw = localStorage.getItem(storageKey); if (raw) { const s = JSON.parse(raw); if (s && typeof s === "object" && s.input) { const i = s.input; setInput({ top20: i.top20 === true, entry: i.entry === "broad" ? "broad" : "tailored", captured: i.captured === true, downloaded: i.captured === true && i.downloaded === true, event: ["none", "registered", "attended"].includes(i.event) ? i.event : "none", meeting: i.captured === true && i.meeting === true }); if (typeof s.role === "string") setRole(s.role); } } } catch { setNotice("Saved demo could not be loaded. You can continue with a fresh simulation."); } setReady(true); }, []);
  useEffect(() => { if (ready) { try { localStorage.setItem(storageKey, JSON.stringify({ input, role })); } catch { setNotice("Browser saving is unavailable. Download the readout to keep this simulation."); } } }, [input, role, ready]);
  const result = finservResult(input);
  function update(patch: Partial<FinservInput>) { setInput(previous => { const next = { ...previous, ...patch }; if (!next.captured) { next.downloaded = false; next.meeting = false; } if (!next.downloaded) next.event = "none"; return next; }); }
  function download() { const text = `# Finserv activation\n\nPrototype simulation; no live outreach or measured results.\n\nOctober–November activation; December follow-through and readout.\n\n${journeys.map(j => `## ${j.title}\n${j.audience}\n${j.steps.join(" → ")}`).join("\n\n")}\n\n## Coordination and working assumptions\nTop 20 contacts remain eligible for broad acquisition. Once identified, tailored follow-up takes priority; suppress duplicate guide emails and competing event invitations. Form submission is distinct from confirmed download. Non-downloaders in both tracks receive relevant proof. Account Directors receive context after a Top 20 download; registration, attendance or a direct meeting request prompts active follow-up.\n\n## Current simulated contact\nRole: ${role}\nTrack: ${result.track}\n${result.history.join("\n")}\nNext action: ${result.next}\nSales: ${result.sales}\n\n## December measurement plan\n${finservMeasures.map(m => `### ${m[0]}\n${m[1]}\nSource: ${m[2]}\nResults: awaiting activation data; targets to be agreed.`).join("\n\n")}\n\nDeduplicate contacts and accounts across tracks for campaign totals. Report Top 20 as a subset, not an additive audience. December: complete event and Sales follow-up, reconcile data, review progression, and assign next actions.\n`; const url = URL.createObjectURL(new Blob([text], { type: "text/markdown" })); const a = document.createElement("a"); a.href = url; a.download = "finserv-workflow-readout.md"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <main className="finserv"><header className="finserv-hero"><div><span className="fs-eyebrow">FINANCIAL SERVICES · CAMPAIGN WORKFLOW</span><h1>One market. Two connected journeys.</h1><p>Build engagement across finance, deepen the Top 20 relationships, and carry the context into Sales.</p><div className="fs-tags"><span>Oct–Nov · Activation</span><span>December · Follow-through + readout</span><span>Prototype · no live outreach</span></div></div><button onClick={download}>Download readout ↗</button></header>
  <nav className="fs-tabs" aria-label="Finserv views">{["Journey", "Test a contact", "December readout"].map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</nav>
  {notice && <p role="status">{notice}</p>}
  {tab === "Journey" && <><div className="fs-grid">{journeys.map(j => <section className="fs-card" key={j.title}><span className="fs-eyebrow">OCTOBER–NOVEMBER</span><h2>{j.title}</h2><p>{j.audience}</p><ol className="fs-steps">{j.steps.map((step, index) => <li key={step}><span>{index + 1}</span>{step}</li>)}</ol><div className="fs-note"><b>No confirmed download?</b><p>Send relevant proof, then offer the guide again. Event invitations wait for a confirmed download.</p></div></section>)}</div><section className="fs-card fs-coordination"><h2>Coordinate the overlap</h2><p>Top 20 prospects can enter through either ad. After email capture identifies a Top 20 contact, use the tailored follow-up and virtual roundtable path. Suppress duplicate guide emails and competing invitations.</p><p><b>Working handoff rule:</b> A confirmed Top 20 download prepares Account Director context. Roundtable registration, attendance, or a direct meeting request prompts active follow-up.</p><p><b>Channels:</b> LinkedIn/paid → web → email → webinar or virtual roundtable → Sales.</p><button onClick={() => setTab("Test a contact")}>Test the routing →</button></section></>}
  {tab === "Test a contact" && <div className="fs-grid"><section className="fs-card"><span className="fs-eyebrow">ILLUSTRATIVE CONTACT · FINANCE PROSPECT</span><h2>Choose the engagement signals</h2><fieldset disabled={!ready}><label>Account segment<select value={input.top20 ? "top20" : "broad"} onChange={e => update({ top20: e.target.value === "top20", entry: "broad" })}><option value="top20">Top 20 account</option><option value="broad">Other finance account</option></select></label><label>Entry journey<select value={input.entry} onChange={e => update({ entry: e.target.value as FinservInput["entry"] })}>{input.top20 && <option value="tailored">Account/persona ad → tailored page</option>}<option value="broad">Prospect ad → financial-workflow page</option></select></label><label>Buying-group role<select value={role} onChange={e => setRole(e.target.value)}>{["Business sponsor", "Technical evaluator", "Procurement lead", "Finance decision-maker"].map(r => <option key={r}>{r}</option>)}</select></label><label className="fs-check"><input type="checkbox" checked={input.captured} onChange={e => update({ captured: e.target.checked })} />Email captured on landing page</label><label className="fs-check"><input type="checkbox" disabled={!input.captured} checked={input.downloaded} onChange={e => update({ downloaded: e.target.checked })} />Guide download confirmed</label><label>Event response<select disabled={!input.downloaded} value={input.event} onChange={e => update({ event: e.target.value as FinservInput["event"] })}><option value="none">Not registered</option><option value="registered">Registered</option><option value="attended">Attended</option></select></label><label className="fs-check"><input type="checkbox" disabled={!input.captured} checked={input.meeting} onChange={e => update({ meeting: e.target.checked })} />Direct meeting request</label><button onClick={() => { setInput(initialFinserv); setRole("Business sponsor"); }}>Reset contact</button></fieldset></section><section className="fs-card" aria-live="polite"><span className="fs-eyebrow">ROUTING PREVIEW</span><h2>{input.captured ? result.track : "Awaiting identification"}</h2><div className="fs-note"><b>Next marketing action</b><p>{result.next}</p></div><div className="fs-note"><b>Sales handoff</b><p>{result.sales}</p></div><h3>Engagement history</h3><ul>{result.history.map(h => <li key={h}>{h}</li>)}</ul>{input.captured && <p><b>Role included in context:</b> {role}</p>}{input.top20 && input.captured && input.entry === "broad" && <p className="fs-note">Matched to Top 20 after capture. Tailored follow-up takes priority; the broader-market webinar invitation is suppressed.</p>}<p className="fs-muted">This simulation demonstrates routing rules. It does not send emails, create CRM tasks, or record actual campaign results.</p></section></div>}
  {tab === "December readout" && <><section className="fs-card"><span className="fs-eyebrow">MEASUREMENT PLAN · RESULTS PENDING</span><h2>Did engagement turn into progression?</h2><p>Compare both journeys, with Top 20 reported as a subset of the inclusive finance audience. Deduplicate contacts and accounts in campaign totals.</p><div className="fs-table-wrap"><table><thead><tr><th>Measure</th><th>December readout</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{finservMeasures.map(m => <tr key={m[0]}><th>{m[0]}</th><td>{m[1]}</td><td>{m[2]}</td><td>Awaiting activation data</td></tr>)}</tbody></table></div><p className="fs-muted">Targets will be agreed once audience sizes, budget and baseline performance are available. No performance figures are assumed.</p></section><div className="fs-grid"><section className="fs-card"><h2>Close the loop in December</h2><ol><li>Deliver event recaps and complete outstanding Account Director follow-ups.</li><li>Reconcile web, email, event and CRM records.</li><li>Review account progression and distinguish sourced from influenced opportunities.</li><li>Assign Sales and nurture next steps; agree changes for the next activation.</li></ol></section><section className="fs-card"><h2>Working assumptions to validate</h2><ul><li>Relevant proof goes to non-downloaders in both tracks.</li><li>Registration, attendance or a meeting request prompts Top 20 Sales follow-up.</li><li>Other finance contacts stay in nurture unless they request a meeting.</li><li>Marketing operations reconciles the readout; Account Directors confirm Sales outcomes.</li></ul></section></div></>}
  </main>;
}
